# Generated by Django 5.2.5 on 2025-09-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0003_alter_customuser_options_transporteur_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='telephone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
