# Generated by Django 5.2.5 on 2025-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0004_transporteur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='vehicule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
