# Generated by Django 5.2.5 on 2025-09-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0006_transporteur_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
