# Generated by Django 5.2.5 on 2025-09-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='utilisateur',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colis',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to=settings.AUTH_USER_MODEL),
        ),
    ]
