# Generated by Django 5.2.5 on 2025-09-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0008_agent_utilisateur_alter_colis_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
