# Generated by Django 5.2.5 on 2025-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0009_colis_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='est_terminee',
        ),
        migrations.AddField(
            model_name='tache',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminé')], max_length=20, null=True),
        ),
    ]
