# Generated by Django 5.2.5 on 2025-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0010_remove_tache_est_terminee_tache_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('expediteur', 'Expéditeur'), ('destinataire', 'Destinataire')], default='', max_length=50),
        ),
    ]
