# Generated by Django 5.2.5 on 2025-09-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0011_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('expediteur', 'Expéditeur'), ('destinataire', 'Destinataire')], default='expediteur', max_length=50),
        ),
    ]
