# Generated by Django 5.2.5 on 2025-09-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0012_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
